name: ready_artisans
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  font_awesome_flutter: ^10.4.0
  flutter_markdown: ^0.6.14
  flutter_native_splash: ^2.2.19
  flutter_smart_dialog: ^4.9.0+4
  provider: ^6.0.5
  image_picker: ^0.8.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geocoding:
  location: ^4.4.0
  carousel_slider: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true
#flutter pub run flutter_native_splash:create
# flutter packages pub run build_runner build

flutter:

  uses-material-design: true


  assets:
    - assets/images/


